version: "3.9"
services:
  deemix:
    image: ghcr.io/bambanah/deemix:latest
    container_name: deemix
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /opt/volumes/filebrowser/deemix:/downloads
    ports:
      - 6595:6595
