version: "3.9"
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    ports:
      - 9443:443
    volumes:
      - snapdrop-config:/config

volumes:
  snapdrop-config:
